services:
  mwmbl-crawler:
    build:
      context: .
      dockerfile: Dockerfile.crawler
    image: mwmbl/crawler
    container_name: mwmbl-crawler
    pull_policy: always
    depends_on:
      - redis
    environment:
      - MWMBL_API_KEY=${MWMBL_API_KEY}
      - CRAWLER_WORKERS=2
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379
    volumes:
      - crawler_data:/root/.mwmbl
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
    # CPU restrictions if needed:
    #     resources:
    #       limits:
    #         cpus: '0.50'

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  crawler_data:
