# .github/workflows/deploy.yml

name: Deploy to Dokku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Dokku
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Don't do a shallow clone (which happens by default)

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Dokku server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan mwmbl.org >> ~/.ssh/known_hosts

      - name: Deploy mwmbl.org
        run: |
          git remote add dokku-mwmbl-org dokku@mwmbl.org:mwmbl.org
          git push dokku-mwmbl-org main --force

      - name: Deploy api.mwmbl.org
        run: |
          git remote add dokku-api-mwmbl-org dokku@mwmbl.org:api.mwmbl.org
          git push dokku-api-mwmbl-org main --force

      - name: Deploy mwmbl-count-urls
        run: |
          git remote add dokku-mwmbl-count-urls dokku@mwmbl.org:mwmbl-count-urls
          git push dokku-mwmbl-count-urls main --force

      - name: Deploy mwmbl-update-batches
        run: |
          git remote add dokku-mwmbl-update-batches dokku@mwmbl.org:mwmbl-update-batches
          git push dokku-mwmbl-update-batches main --force

      - name: Deploy mwmbl-update-urls
        run: |
          git remote add dokku-mwmbl-update-urls dokku@mwmbl.org:mwmbl-update-urls
          git push dokku-mwmbl-update-urls main --force
